[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pipeline"
version = "0.1.0"
description = "Thesis experimental pipeline project"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "networkx",
    "cdlib",
    "scikit-fuzzy"
]

[project.scripts]
pipeline = "pipeline.__main__:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]